import torch
import re
import pandas as pd
from transformers import AutoModelForCausalLM, AutoProcessor
from datasets import load_dataset
from tqdm import tqdm

# Fix for PyTorch Dynamo compilation crash with Gemma 3
import torch._dynamo 
torch._dynamo.config.disable = True

def extract_ground_truth(answer_str):
    """Extracts the final numerical answer from the GSM8K ground truth string."""
    if "#### " in answer_str:
        return answer_str.split("#### ")[-1].replace(",", "").strip()
    return None

def extract_model_prediction(generated_text):
    match = re.search(r'<answer>(.*?)</answer>', generated_text)
    if match:
        # Extract the number and strip commas
        number_str = re.sub(r'[^\d.-]', '', match.group(1))
        return number_str
    return None

def evaluate_prompt(model, tokenizer, dataset_split, system_prompt, batch_size=16):
    """Evaluates a single prompt against the dataset split using batching."""
    
    correct = 0
    total = len(dataset_split)
    
    # Process in batches for GPU efficiency
    for i in tqdm(range(0, total, batch_size), desc=f"Evaluating prompt"):
        batch = dataset_split[i : i + batch_size]
        questions = batch["question"]
        ground_truths = [extract_ground_truth(ans) for ans in batch["answer"]]
        
        # Format the chat template for the entire batch
        batch_messages = [
            [
                {"role": "system", "content": f"{system_prompt} \n Wrap your final numerical answer in XML tags like this: <answer>9</answer>\n"},
                {"role": "user", "content": q}
            ] 
            for q in questions
        ]
        
        # Apply chat template and pad the batch
        formatted_prompts = tokenizer.apply_chat_template(
            batch_messages, 
            tokenize=False, 
            add_generation_prompt=True
        )
        
        # Explicitly pass text= for the multimodal processor
        inputs = tokenizer(
            text=formatted_prompts, 
            return_tensors="pt", 
            padding=True, 
            truncation=True
        ).to(model.device)
        
        # Generate the answers
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=1024, # Increased to allow CoT to finish
                do_sample=False,     # Greedy decoding (removed temperature to avoid warnings)
                pad_token_id=tokenizer.tokenizer.eos_token_id
            )
            
        # We only want to decode the *new* generated tokens, not the prompt
        input_length = inputs.input_ids.shape[1]
        generated_tokens = outputs[:, input_length:]
        
        responses = tokenizer.batch_decode(generated_tokens, skip_special_tokens=True)
        
        # Compare predictions to ground truths
        for response, truth in zip(responses, ground_truths):
            prediction = extract_model_prediction(response)
            
            # Check if the extracted prediction matches the truth
            if prediction == truth:
                correct += 1

    accuracy = correct / total
    return accuracy

def main():
    device = torch.device("cuda:3") # Your 4th GPU
    
    # Load dataset
    dataset = load_dataset("gsm8k", "main")
    
    # We evaluate on the TEST split (1,319 examples)
    test_set = dataset["test"]
    
    # If you want to do a fast dry-run first, uncomment the next line:
    # test_set = test_set.select(range(100)) 
    
    # Load Model (Updated to Gemma 3)
    model_id = "google/gemma-3-12b-it"
    print(f"Loading {model_id}...")
    
    # Use AutoProcessor instead of AutoTokenizer
    tokenizer = AutoProcessor.from_pretrained(model_id, padding_side="left")
    
    if tokenizer.tokenizer.pad_token is None:
        tokenizer.tokenizer.pad_token = tokenizer.tokenizer.eos_token
        
    model = AutoModelForCausalLM.from_pretrained(
        model_id, 
        device_map=device, 
        torch_dtype=torch.bfloat16
    ).eval()
    
    # Paste the final prompts generated by your optimization script here
    prompts_to_test = {
        "Baseline" : "Please answer the following questions as accurately as possible. Think step-by-step and provide reasoning for your solutions. Double-check your answers and list your thoughts clearly.",
        "Refined Baseline": "Think.",
    }
    results = {}
    
    for name, prompt in prompts_to_test.items():
        print(f"\n--- Testing: {name} ---")
        accuracy = evaluate_prompt(model, tokenizer, test_set, prompt, batch_size=16)
        results[name] = accuracy
        print(f"Accuracy for {name}: {accuracy * 100:.2f}%")
        
    print("\n=== FINAL RESULTS ===")
    for name, acc in results.items():
        print(f"{name}: {acc * 100:.2f}%")

if __name__ == "__main__":
    main()